### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by RomanSoviak** [erickok/app_set_id#7]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getIdentifier on channel app_set_id)
E/flutter (20795): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
E/flutter (20795): <asynchronous suspension>
E/flutter (20795): #1      MethodChannelAppSetId.getIdentifier (package:app_set_id/app_set_id_method_channel.dart:15:9)
E/flutter (20795): <asynchronous suspension>
```

`  app_set_id: ^1.2.1
`

**Comment by erickok** [comment]
Probably just have to run `flutter pub upgrade`. What platform have you received this error on?

**Comment by RomanSoviak** [comment]
I run app on debug - I'll try in the release mode and will write back soon
